# Generated by Django 3.2.4 on 2021-06-28 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webCaosNews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodista',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('lead', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('cuerpo', models.CharField(max_length=100)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webCaosNews.categoria')),
                ('Periodista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webCaosNews.periodista')),
            ],
        ),
    ]
