# Generated by Django 3.2.4 on 2021-06-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCaosNews', '0002_noticia_periodista_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
