# Generated by Django 3.2.4 on 2021-06-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCaosNews', '0003_auto_20210629_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imgNoticia'),
        ),
    ]
