# Generated by Django 3.2.4 on 2021-06-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCaosNews', '0004_noticia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
