# Generated by Django 3.2.4 on 2021-06-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCaosNews', '0006_noticia_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(default='imgNoticia/noDisponible.png', upload_to='imgNoticia'),
        ),
    ]
