# Generated by Django 3.2.4 on 2021-06-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCaosNews', '0007_alter_noticia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='periodista',
            field=models.TextField(default='-'),
        ),
    ]
