# Generated by Django 3.2.4 on 2021-06-30 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webCaosNews', '0008_noticia_periodista'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='Periodista',
        ),
        migrations.DeleteModel(
            name='Periodista',
        ),
    ]
